### ISSUE TITLE
Selection List Becomes non Clickable (Not Interactive)

### ISSUE THREAD

**Issue by Hashir524** [yonat/SelectionList#2]
So I tested the library in a sample project and it's working fine. when i integrated it in my project. it becomes non interactive?

**Comment by yonat** [comment]
How do you get it to be non-responsive?
What are the steps to reproduce this behavior?

**Comment by Hashir524** [comment]
As of now, i couldn't figure out the issue. I don't know why it became non-responsive. i spent a whole day figuring that out, but no luck. At last I made the whole screen from the scratch, with selection list placed from the start. Now it's working. Sorry for the issue. Good Library it helped me. 👍
